definition:
  type: SimpleIdentifier
  instanceOf: DevboardLib\GitHub\Application\ApplicationId
  parent: ~
  interfaces: {  }
  traits: {  }
  constructor:
    id:
      instanceOf: int
      nullable: false
      hasDefault: false
      default: null
      examples: [177]
